### ISSUE TITLE
Confirmation of dash version...

### ISSUE THREAD

**Issue by darksidelemm** [krakenrf/krakensdr_doa#24]
I'm attempting to set up krakensdr_doa on an intel NUC, due to having experienced big RFI issues with RPi4's.

After following the instructions [here](https://github.com/krakenrf/krakensdr_doa#manual-installation-from-a-fresh-os) verbatim, I end up at the point where i startup the software, but the main webserver on port 8080 doesn't start, with the following error:

```
(kraken) darkside@darkside-nuc:~/krakensdr/krakensdr_doa$ cat ui.log 
Traceback (most recent call last):
  File "/home/darkside/krakensdr/krakensdr_doa/_UI/_web_interface/kraken_web_interface.py", line 82, in <module>
    import tooltips
  File "/home/darkside/krakensdr/krakensdr_doa/_UI/_web_interface/tooltips.py", line 2, in <module>
    import dash_bootstrap_components as dbc
  File "/home/darkside/miniforge3/envs/kraken/lib/python3.9/site-packages/dash_bootstrap_components/__init__.py", line 7, in <module>
    from dash_bootstrap_components._table import _generate_table_from_df
  File "/home/darkside/miniforge3/envs/kraken/lib/python3.9/site-packages/dash_bootstrap_components/_table.py", line 5, in <module>
    from dash import html
ImportError: cannot import name 'html' from 'dash' (/home/darkside/miniforge3/envs/kraken/lib/python3.9/site-packages/dash/__init__.py)
```

I can confirm that the dash version is the one specified in the installation instructions (1.20.0):
```
>>> import dash
>>> dash.__version__
'1.20.0'
```

Is this actually the version that is required, or are these instructions out of date?

**Comment by krakenrf** [comment]
Can you paste your "conda list" here? Seems to be something different with dash_bootstrap_components. Maybe they changed dependencies which breaks things.

On my working Kraken systems dash_bootstrap_components is version 1.1.0, try installing that version if you have 1.2.0.

**Comment by darksidelemm** [comment]
Yep.. v1.2.0 for dash_bootstrap_components, which is what pip3 brought in.
Pinned that to 1.1.0 and i can now import html now, and the webserver starts.

However, now when I navigate to the web interface, I just get a black page, and the following error in the JS console:
<img width="473" alt="Screen Shot 2022-07-11 at 15 38 19" src="https://user-images.githubusercontent.com/1040275/178199524-44cc6200-28ec-4895-9bca-91ebcf03584f.png">



```
(kraken) darkside@darkside-nuc:~/krakensdr/krakensdr_doa$ conda list
# packages in environment at /home/darkside/miniforge3/envs/kraken:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
aiofiles                  0.8.0              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      2.106                       mkl    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     2.4.3            py39hf3d152e_0    conda-forge
brotli                    1.0.9                    pypi_0    pypi
brotli-bin                1.0.9                h166bdaf_7    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15        py39hf3d152e_0    conda-forge
cffi                      1.15.1           py39he91dace_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hf3d152e_0    conda-forge
configparser              5.2.0              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4           py39hd97740a_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dash                      1.20.0                   pypi_0    pypi
dash-bootstrap-components 1.2.0                    pypi_0    pypi
dash-core-components      1.16.0                   pypi_0    pypi
dash-devices              0.1.3                    pypi_0    pypi
dash-html-components      1.1.3                    pypi_0    pypi
dash-renderer             1.9.1                    pypi_0    pypi
dash-table                4.11.3                   pypi_0    pypi
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
flask                     2.1.2                    pypi_0    pypi
flask-compress            1.12                     pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.34.4           py39hb9d737c_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py39hf3d152e_5    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.70.2               h780b84a_4    conda-forge
glib-tools                2.70.2               h780b84a_4    conda-forge
gst-plugins-base          1.20.3               hf6a322e_0    conda-forge
gstreamer                 1.20.3               hd4edc92_0    conda-forge
h11                       0.13.0             pyhd8ed1ab_1    conda-forge
h2                        4.1.0            py39hf3d152e_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hypercorn                 0.13.2           py39hf3d152e_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icc_rt                    2020.2                intel_254    numba
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39hf3d152e_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
ipython                   8.4.0            py39hf3d152e_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1           py39hf3d152e_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.3            py39hf939315_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0                     6_mkl    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0                     6_mkl    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libdeflate                1.12                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                     6_mkl    conda-forge
liblapacke                3.9.0                     6_mkl    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm13                 13.0.1               hf817b99_2    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h753d276_3    conda-forge
libpq                     14.4                 hd77ab85_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                hc85c160_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.43.0               h7f98852_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.12               h166bdaf_1    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
llvmlite                  0.36.0           py39h1bbdace_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.1.1            py39hb9d737c_1    conda-forge
matplotlib                3.5.2            py39hf3d152e_0    conda-forge
matplotlib-base           3.5.2            py39h700656a_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.29               haf5c9bc_1    conda-forge
mysql-libs                8.0.29               h28c427c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numba                     0.53.1           py39h56b8d98_1    conda-forge
numpy                     1.23.1           py39hba7629e_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
orjson                    3.7.7            py39hb9d737c_0    conda-forge
outcome                   1.2.0              pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py39h1832856_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py39hae2aec6_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
plotly                    5.9.0                    pypi_0    pypi
ply                       3.11                       py_1    conda-forge
priority                  2.0.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyargus                   1.1.post1                pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyface                    7.4.1              pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39h03dd644_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtgraph                 0.12.4             pyhd8ed1ab_0    conda-forge
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1            py39hf3d152e_5    conda-forge
python                    3.9.7           hb7a2778_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyvisa                    1.12.0           py39hf3d152e_0    conda-forge
pyyaml                    6.0              py39hb9d737c_4    conda-forge
pyzmq                     23.2.0           py39headdf64_0    conda-forge
qt                        5.12.9               h1304e3e_6    conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
quart                     0.17.0             pyhd8ed1ab_0    conda-forge
quart-compress            0.2.1                    pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
scikit-rf                 0.23.0             pyhd8ed1ab_0    conda-forge
scipy                     1.8.1            py39he49c0e8_0    conda-forge
setuptools                63.1.0           py39hf3d152e_0    conda-forge
sip                       6.6.2            py39h5a03fae_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0            py39hf3d152e_3    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.39.0               h4ff8645_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
tenacity                  8.0.1                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py39hb9d737c_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
traits                    6.3.2            py39hb9d737c_1    conda-forge
traitsui                  7.4.0              pyhd8ed1ab_0    conda-forge
trio                      0.21.0           py39hf3d152e_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py39hb9d737c_1    conda-forge
urllib3                   1.26.10            pyhd8ed1ab_0    conda-forge
uvloop                    0.16.0           py39h3811e60_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wsproto                   1.1.0            py39hf3d152e_1    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_1    conda-forge
zstd                      1.5.2                h8a70e8d_2    conda-forge
```

**Comment by darksidelemm** [comment]
Ahh... pinning dash_bootstrap_components to 1.1.0 resulted in dash itself getting updated by pip3:
```
Successfully installed dash-2.5.1 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0
```

After re-running `conda install dash==1.20.0` and `conda install werkzeug==2.0.2` (in which conda complains a bit) I end up with a web interface that seems to work. 

Might be worth updating the documentation, because i'm sure others are going to hit this problem...

**Comment by krakenrf** [comment]
Ah was just about the suggest that.

Yeah dash versioning is going to be an annoying problem with them depreciating a lot of things that dash_devices works with, and dash_devices seems abandoned these days. I guess we just pin everything to versions that work.

Although, I just tested a fresh install with pip3 install dash_bootstrap_components and got v1.2.0 and I had no problems running. So something weird is happening with conda and pip3 interacting weirdly on some systems.
